### ISSUE TITLE
APK download link not working.

### ISSUE THREAD

**Issue by AngeloBenjamin0** [kamui-7/rin#2]

**Comment by kamui-fin** [comment]
Hey, I just switched from Drive to Github Releases so you can find it [here](https://github.com/kamui-7/rin/releases/download/v0.1.0/rin-v0.1.0.apk).

**Comment by austinhuang0131** [comment]
There does not seem to be any GitHub releases?

**Comment by kamui-fin** [comment]
@austinhuang0131 It should be there now
